language: php

php:
  - 8.1
  - 8.2

before_script:
  - composer --prefer-source install

script:
  - ./vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml

after_script:
  - ./vendor/bin/test-reporter --coverage-report ./build/logs/clover.xml
